INSERT INTO distro (name, based_on) VALUES ('Ubuntu', 'Debian');
INSERT INTO distro (name, based_on) VALUES ('Fedora', 'Independent');
INSERT INTO distro (name, based_on) VALUES ('Arch Linux', 'Independent');
INSERT INTO distro (name, based_on) VALUES ('openSUSE', 'Independent');
INSERT INTO distro (name, based_on) VALUES ('CentOS', 'RHEL');
INSERT INTO distro (name, based_on) VALUES ('Debian', 'Independent');
INSERT INTO distro (name, based_on) VALUES ('Linux Mint', 'Ubuntu');
INSERT INTO distro (name, based_on) VALUES ('Manjaro', 'Arch Linux');
INSERT INTO distro (name, based_on) VALUES ('elementary OS', 'Ubuntu');
INSERT INTO distro (name, based_on) VALUES ('Gentoo', 'Independent');
INSERT INTO distro (name, based_on) VALUES ('Pop!_OS', 'Ubuntu');
INSERT INTO distro (name, based_on) VALUES ('Solus', 'Independent');
INSERT INTO distro (name, based_on) VALUES ('Fedora Silverblue', 'Fedora');
INSERT INTO distro (name, based_on) VALUES ('Kali Linux', 'Debian');
INSERT INTO distro (name, based_on) VALUES ('Zorin OS', 'Ubuntu');
INSERT INTO distro (name, based_on) VALUES ('MX Linux', 'Debian');
INSERT INTO distro (name, based_on) VALUES ('Slackware', 'Independent');
INSERT INTO distro (name, based_on) VALUES ('ArchBang', 'Arch Linux');
INSERT INTO distro (name, based_on) VALUES ('Void Linux', 'Independent');
INSERT INTO distro (name, based_on) VALUES ('FreeBSD', 'Independent');