server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distro_contrast
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: storage

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq

events:
  resource:
    queues:
      new-device-queue: DISTRO_CONTRAST_NEW_DEVICE_BY_USER
      tests-queue: DISTRO_CONTRAST_NEW_TESTS_BY_DEVICE