server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/distro_contrast
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: storage

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
